## Mean-Variance-Standard Deviation Calculator

Assignment
Create a function named calculate() in mean_var_std.py that uses Numpy to output the mean, variance, standard deviation, max, min, and sum of the rows, columns, and elements in a 3 x 3 matrix.

The input of the function should be a list containing 9 digits. The function should convert the list into a 3 x 3 Numpy array, and then return a dictionary containing the mean, variance, standard deviation, max, min, and sum along both axes and for the flattened matrix.

The returned dictionary should follow this format:

    {
      'mean': [axis1, axis2, flattened],
      'variance': [axis1, axis2, flattened],
      'standard deviation': [axis1, axis2, flattened],
      'max': [axis1, axis2, flattened],
      'min': [axis1, axis2, flattened],
      'sum': [axis1, axis2, flattened]
    }
    {
      'mean': [axis1, axis2, flattened],
      'variance': [axis1, axis2, flattened],
      'standard deviation': [axis1, axis2, flattened],
      'max': [axis1, axis2, flattened],
      'min': [axis1, axis2, flattened],
      'sum': [axis1, axis2, flattened]
    }
    
If a list containing less than 9 elements is passed into the function, it should raise a ValueError exception with the message: "List must contain nine numbers." The values in the returned dictionary should be lists and not Numpy arrays.

For example, calculate([0,1,2,3,4,5,6,7,8]) should return:

    {
      'mean': [[3.0, 4.0, 5.0], [1.0, 4.0, 7.0], 4.0], 
      'variance': [[6.0, 6.0, 6.0], [0.6666666666666666, 0.6666666666666666, 0.6666666666666666], 6.666666666666667], 
      'standard deviation': [[2.449489742783178, 2.449489742783178, 2.449489742783178], [0.816496580927726, 0.816496580927726, 0.816496580927726], 2.581988897471611],
      'max': [[6, 7, 8], [2, 5, 8], 8],
      'min': [[0, 1, 2], [0, 3, 6], 0],
      'sum': [[9, 12, 15], [3, 12, 21], 36]}
    }
    {
      'mean': [[3.0, 4.0, 5.0], [1.0, 4.0, 7.0], 4.0], 
      'variance': [[6.0, 6.0, 6.0], [0.6666666666666666, 0.6666666666666666, 0.6666666666666666], 6.666666666666667], 
      'standard deviation': [[2.449489742783178, 2.449489742783178, 2.449489742783178], [0.816496580927726, 0.816496580927726, 0.816496580927726], 2.581988897471611],
      'max': [[6, 7, 8], [2, 5, 8], 8],
      'min': [[0, 1, 2], [0, 3, 6], 0],
      'sum': [[9, 12, 15], [3, 12, 21], 36]}
    }
The unit tests for this project are in test_module.py.

Development
For development, you can use main.py to test your calculate() function. Click the "run" button and main.py will run.

Testing
We imported the tests from test_module.py to main.py for your convenience. The tests will run automatically whenever you hit the "run" button.

Submitting
Copy your project's URL and submit it to freeCodeCamp.

In [20]:
import numpy as np

def calculate(list):

  if len(list) < 9 or len(list) > 9:
    #return "List must contain nine numbers."
    raise ValueError("List must contain nine numbers.")

  else:
    list = np.array(list).reshape(3, 3)
    print(list, "\n")

    
    new_dict = dict()
    
    a = np.mean(list, axis=0).tolist()
    b = np.mean(list, axis=1).tolist()
    new_dict['mean'] = [a, b, np.mean(list)]
    
    a = np.var(list, axis=0).tolist()
    b = np.var(list, axis=1).tolist()
    new_dict['variance'] = [a, b, np.var(list)]
    
    a = np.std(list, axis=0).tolist()
    b = np.std(list, axis=1).tolist()
    c = np.std(list)
    new_dict['standard deviation'] = [a, b, c]
    
    a = np.max(list, axis=0).tolist()
    b = np.max(list, axis=1).tolist()
    c = np.max(list)
    new_dict['max'] = [a, b, c]
    
    a = np.min(list, axis=0).tolist()
    b = np.min(list, axis=1).tolist()
    c = np.min(list)
    new_dict['min'] = [a, b, c]
    
    a = np.sum(list, axis=0).tolist()
    b = np.sum(list, axis=1).tolist()
    c = np.sum(list)
    new_dict['sum'] = [a, b, c]
    
    # YES!
    # https://stackoverflow.com/questions/60051461/how-to-get-numpy-array-values
    
    #my_dict = {"mean":[a.tolist()],"variance":[],"std":[], 'max':[], 'min':[], 'sum':[]};
    #print("\n :(((((", my_dict, "\n\n")
    
    print(np.mean(list, axis=0), "\n")
    

    return new_dict


print(calculate([0,1,2,3,4,5,6,7,8]))

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[3. 4. 5.] 

{'mean': [[3.0, 4.0, 5.0], [1.0, 4.0, 7.0], 4.0], 'variance': [[6.0, 6.0, 6.0], [0.6666666666666666, 0.6666666666666666, 0.6666666666666666], 6.666666666666667], 'standard deviation': [[2.449489742783178, 2.449489742783178, 2.449489742783178], [0.816496580927726, 0.816496580927726, 0.816496580927726], 2.581988897471611], 'max': [[6, 7, 8], [2, 5, 8], 8], 'min': [[0, 1, 2], [0, 3, 6], 0], 'sum': [[9, 12, 15], [3, 12, 21], 36]}


## Demographic Data Analyzer

In this challenge you must analyze demographic data using Pandas. You are given a dataset of demographic data that was extracted from the 1994 Census database. Here is a sample of what the data looks like:

 |id| age | workclass | fnlwgt           | education | education-num | marital-status | occupation         | relationship      | race          | sex   | capital-gain | capital-loss | hours-per-week | native-country | salary        |
 |---| --- | :-------: | ---------------- | --------- | ------------- | -------------- | ------------------ | ----------------- | ------------- | ----- | ------------ | ------------ | -------------- | -------------- | ------------- |
 | 0   |    39     | State-gov        | 77516     | Bachelors     | 13             | Never-married      | Adm-clerical      | Not-in-family | White | Male         | 2174         | 0              | 40             | United-States | <=50K |
 | 1   |    50     | Self-emp-not-inc | 83311     | Bachelors     | 13             | Married-civ-spouse | Exec-managerial   | Husband       | White | Male         | 0            | 0              | 13             | United-States | <=50K |
 | 2   |    38     | Private          | 215646    | HS-grad       | 9              | Divorced           | Handlers-cleaners | Not-in-family | White | Male         | 0            | 0              | 40             | United-States | <=50K |
 | 3   |    53     | Private          | 234721    | 11th          | 7              | Married-civ-spouse | Handlers-cleaners | Husband       | Black | Male         | 0            | 0              | 40             | United-States | <=50K |
 | 4   |    28     | Private          | 338409    | Bachelors     | 13             | Married-civ-spouse | Prof-specialty    | Wife          | Black | Female       | 0            | 0              | 40             | Cuba          | <=50K |
 

You must use Pandas to answer the following questions:

- How many people of each race are represented in this dataset? This should be a Pandas series with race names as the index labels. (race column)
- What is the average age of men?
- What is the percentage of people who have a Bachelor's degree?
- What percentage of people with advanced education (Bachelors, Masters, or Doctorate) make more than 50K?
- What percentage of people without advanced education make more than 50K?
- What is the minimum number of hours a person works per week?
- What percentage of the people who work the minimum number of hours per week have a salary of more than 50K?
- What country has the highest percentage of people that earn >50K and what is that percentage?
- Identify the most popular occupation for those who earn >50K in India.

Use the starter code in the file demographic_data_anaylizer. Update the code so all variables set to "None" are set to the appropriate calculation or code. Round all decimals to the nearest tenth.

Unit tests are written for you under test_module.py.

##### Development
For development, you can use main.py to test your functions. Click the "run" button and main.py will run.

##### Testing
We imported the tests from test_module.py to main.py for your convenience. The tests will run automatically whenever you hit the "run" button.

##### Submitting
Copy your project's URL and submit it to freeCodeCamp.

#####  Dataset Source
Dua, D. and Graff, C. (2019). UCI Machine Learning Repository [http://archive.ics.uci.edu/ml]. Irvine, CA: University of California, School of Information and Computer Science.

In [61]:
import pandas as pd


def calculate_demographic_data(print_data=True):
    # Read data from file
    df = pd.read_csv('adult.data.csv')

    # How many of each race are represented in this dataset? This should be a Pandas series with race names as the index labels.
    # print("\n", df.groupby(by='race').agg('count'), "\n")
    # print("\n", df['race'].value_counts(), "\n")
    race_count = df['race'].value_counts()

    # What is the average age of men?
    average_age_men = df.loc[df['sex']=='Male', ['age']].mean()
    # print("\n", df.groupby('sex').mean() ,"\n")
    # print("\n", df.loc[df['sex']=='Male', ['age', 'sex']].mean() ,"\n")
    # print("\n", df.loc[df['sex'] == 'Male'].mean() ,"\n")

    # What is the percentage of people who have a Bachelor's degree?
    # print("\n", df['education'].count(), "\n") # total people by education
    # print("\n", df.loc[df['education']=='Bachelors', ['education']].count()) # people with bachelors
    n_positions = df['education'].count()
    n_bachelors = df.loc[df['education']=='Bachelors', ['education']].count()
    percentage_bachelors = (n_bachelors / n_positions)*100
    # print("\n\n", percentage_bachelors, "\n\n")
    # print("\n\n", percentage_bachelors.values, "\n\n")
    # print("\n\n", list(percentage_bachelors), "\n\n")

    # What percentage of people with advanced education (`Bachelors`, `Masters`, or `Doctorate`) make more than 50K?
    # What percentage of people without advanced education make more than 50K?

    # with and without `Bachelors`, `Masters`, or `Doctorate`
    print("\n\neducation:\n", df['education'].value_counts(), "\n\n")
    print("\n\n\n\neducation:\n", \
          df[(df['education']=='Bachelors') | \
             (df['education']=='Masters')   | \
             ((df['education']=='Doctorate')) \
            ].count(), \
          "\n\n\n\n")

    
    higher_education = None
    lower_education = None

    # percentage with salary >50K
    print("\n\neducation:\n", df[['education', 'salary']], "\n\n")
    total = df['salary'].count()
    print("*******\ntotal: ", total)
    above_50K = df.loc[df['salary'] == '>50K', ['salary']].count()
    print("***********\nabove 50K: ", above_50K)
    below_50K = df.loc[df['salary'] == '<=50K', ['salary']].count()
    print("***********\nbelow 50K: ", below_50K[0], "\n\n")
    higher_education_rich = (above_50K / total) * 100
    lower_education_rich = (below_50K / total) * 100

    # What is the minimum number of hours a person works per week (hours-per-week feature)?
    min_work_hours = None

    # What percentage of the people who work the minimum number of hours per week have a salary of >50K?
    num_min_workers = None

    rich_percentage = None

    # What country has the highest percentage of people that earn >50K?
    highest_earning_country = None
    highest_earning_country_percentage = None

    # Identify the most popular occupation for those who earn >50K in India.
    top_IN_occupation = None
    
    
    
    print(df)

    
    
    # DO NOT MODIFY BELOW THIS LINE

    if print_data:
        print("Number of each race:\n", race_count) 
        print("Average age of men:", average_age_men)
        print(f"Percentage with Bachelors degrees: {percentage_bachelors}%")
        print(f"Percentage with higher education that earn >50K: {higher_education_rich}%")
        print(f"Percentage without higher education that earn >50K: {lower_education_rich}%")
        print(f"Min work time: {min_work_hours} hours/week")
        print(f"Percentage of rich among those who work fewest hours: {rich_percentage}%")
        print("Country with highest percentage of rich:", highest_earning_country)
        print(f"Highest percentage of rich people in country: {highest_earning_country_percentage}%")
        print("Top occupations in India:", top_IN_occupation)

    return {
        'race_count': race_count,
        'average_age_men': average_age_men,
        'percentage_bachelors': percentage_bachelors,
        'higher_education_rich': higher_education_rich,
        'lower_education_rich': lower_education_rich,
        'min_work_hours': min_work_hours,
        'rich_percentage': rich_percentage,
        'highest_earning_country': highest_earning_country,
        'highest_earning_country_percentage':
        highest_earning_country_percentage,
        'top_IN_occupation': top_IN_occupation
    }


calculate_demographic_data()



education:
 HS-grad         10501
Some-college     7291
Bachelors        5355
Masters          1723
Assoc-voc        1382
11th             1175
Assoc-acdm       1067
10th              933
7th-8th           646
Prof-school       576
9th               514
12th              433
Doctorate         413
5th-6th           333
1st-4th           168
Preschool          51
Name: education, dtype: int64 




TypeError: '(0         True
1         True
2        False
3        False
4         True
         ...  
32556    False
32557    False
32558    False
32559    False
32560    False
Name: education, Length: 32561, dtype: bool, ['education'])' is an invalid key